### ISSUE TITLE
Whoops\Exception\ErrorException: Class 'Zoop\Zoop'

### ISSUE THREAD

**Issue by andrekutianski** [italodeveloper/zoop-sdk#7]
Ao implementar a biblioteca em ambiente Laravel 5.2 PHP 7.2 obtenho apenas o seguinte retorno:

`
Whoops\Exception\ErrorException: Class 'Zoop\Zoop not found in /lib/vendor/italodeveloper/zoop-sdk/src/ZoopClient.php:39
`

**Comment by devath0** [comment]
Amigo execute o optimized autoload: 
```php
composer dumpautoload -o
````
